### ISSUE TITLE
How to install in Gnome?

### ISSUE THREAD

**Issue by zkanda** [ojbucao/Workman#29]
Hello,

I have Archlinux with DE of Gnome. I really want to use Workman but I cannot find any guide on how to do that. Any help would be much appreciated.

**Comment by zkanda** [comment]
I found it. Seems like it's just buried in the input sources.

**Comment by MaxVerevkin** [comment]
It seems not to work anymore?

**Comment by joel0** [comment]
@MaxVerevkin can you describe what you have tried or what isn't working for you?  I set up a fresh install of Arch with Gnome and in the keyboard settings I find "English (Workman)" and it works for me.

![image](https://user-images.githubusercontent.com/8691351/200735618-f36c524a-ba77-4909-951e-9d849de28ba8.png)

**Comment by MaxVerevkin** [comment]
@joel0 thank you for reply. Yes, workman is preinstalled, but I tried to install workman-p. I've run `sudo cp workman-p /usr/share/X11/xkb/symbols/workman-p`, after which I could use workman-p in `sway` and `river` (both are wayland WMs/compositors) but not in gnome.

**Comment by joel0** [comment]
@MaxVerevkin Ah, it seems to be that workman-p is preinstalled too (on Arch)*, but hidden by default.  From `gnome-tweaks`, go to "Keyboard & Mouse", and enabled "Show Extended Input Sources".  Then after restarting, you should be able to find "English (Workman-P)" as an input source you can add.  Hope this helps.

`*` If you want to verify that it's included: `grep workman-p /usr/share/X11/xkb/symbols/us`
