### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by mongrelion** [ojbucao/Workman#31]
I'm trying to access the workmanlayout.com website but I keep getting 
![1hhor](https://cloud.githubusercontent.com/assets/196122/20456095/6f806510-ae6d-11e6-862f-76b75ee935f9.png)

**Comment by SeabassWells** [comment]
Any update on this? 

Also -- the images are down on the description article -- https://viralintrospection.wordpress.com/2010/09/06/a-different-philosophy-in-designing-keyboard-layouts/. Would love to be able to see them.

**Comment by mdbijl** [comment]
I contacted the hoster Justhost. The site is offline due to unpaid bills. They're not very helpful to get me in contact with Oj Bucao, nor are they accepting my money to get the site up again.

Would really hate to see the site disappearing as it means less new Workman users.

**Comment by rasisin** [comment]
This is a problem--there seems to be a critical mass of people using Workman, but no one has been spreading the word and working on development (of OS implementations etc.) since Bucao lost interest around 2014. I'm not an IT professional--since the content of the original site is available cached/archived and the site, is no longer being paid for, is it possible to recreate the site under a different host? Or maybe use a new domain name like "workmankeyboard.net"?

**Comment by mongrelion** [comment]
@rasisin we could host it as a Github page, but for that we're either going to need the original content or at least the original images and we can then build something that can put them together.

**Comment by twhiston** [comment]
The wayback machine has a copy of the site that it would be pretty easy to build something new from https://web.archive.org/web/20160801142148/http://www.workmanlayout.com/blog/

**Comment by stianeklund** [comment]
I second this, we definitely need to get a copy & create a stand in replacement for the original website until we get a response from Bucao. I'm more than willing to help here as well.

**Comment by kdeloach** [comment]
I've been using the Workman keyboard layout for the past 3 years and can't say enough good things about it. To help preserve this information, I have decided to create a backup website. 

I copied the content from Bucao's original article, with minor formatting changes. The website is hosted by GitHub Pages.

http://workmanlayout.org/

**Comment by mdbijl** [comment]
Thank you, really appreciated!!

**Comment by mdbijl** [comment]
One minor remark: image resolutions seem to be low (at least at Mac with retina screen).

**Comment by kdeloach** [comment]
If anyone is able to find or create higher resolution imagery please let me know. Pull requests are more than welcome.

**Comment by stianeklund** [comment]
@kdeloach You can find slightly higher resolution images indexed by Archive.org, http://web.archive.org/web/20160921040508/http://www.workmanlayout.com/blog/ I haven't found anything with better resolution than this, but at least it seems to be an improvement.

**Comment by kdeloach** [comment]
Thanks for the feedback. I increased the width of the content area to prevent image scaling.

**Comment by mongrelion** [comment]
@kdeloach awesome! where's the sauce, btw?

**Comment by mongrelion** [comment]
Nevermind. I found it :)

I'm going to mark this issue as closed as I'm quite satisfied with the outcome.

Thanks everyone for your input and help.
